# Generated by Django 3.2.18 on 2023-05-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate360', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityplanning',
            name='road_width',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='道路幅(m)'),
        ),
    ]
