# Generated by Django 3.2.18 on 2023-05-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate360', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildinginformation',
            name='building_confirmation_screen',
            field=models.CharField(max_length=100, verbose_name='建物確認図面'),
        ),
        migrations.AlterField(
            model_name='buildinginformation',
            name='building_drawing',
            field=models.CharField(max_length=100, verbose_name='建物図面取得'),
        ),
    ]
