# Generated by Django 3.2.18 on 2023-05-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate360', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinformation',
            name='address',
            field=models.CharField(max_length=255, verbose_name='住所地'),
        ),
        migrations.AlterField(
            model_name='buildinginformation',
            name='type_of_rights',
            field=models.CharField(max_length=100, verbose_name='権利の種類'),
        ),
    ]
