# Generated by Django 3.2.18 on 2023-05-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate360', '0002_auto_20230519_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinformation',
            name='control_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='管理番号'),
        ),
    ]
