# Generated by Django 3.2.18 on 2023-05-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate360', '0002_auto_20230505_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinformation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='アクティブ'),
        ),
    ]
